export enum CronExpression {
    EVERY_MINUTE = '* * * * *',
    EVERY_10_MINUTES = '*/10 * * * *',
    EVERY_30_MINUTES = '*/30 * * * *',
    EVERY_HOUR = '0 * * * *',
    EVERY_2_HOURS = '0 */2 * * *',
    EVERY_3_HOURS = '0 */3 * * *',
    EVERY_6_HOURS = '0 */6 * * *',
    EVERY_12_HOURS = '0 */12 * * *',
    EVERY_DAY_AT_MIDNIGHT = '0 0 * * *',
    EVERY_DAY_AT_1AM = '0 1 * * *',
    EVERY_DAY_AT_2AM = '0 2 * * *',
    EVERY_DAY_AT_3AM = '0 3 * * *',
    EVERY_DAY_AT_6AM = '0 6 * * *',
    EVERY_DAY_AT_NOON = '0 12 * * *',
    EVERY_WEEKEND_AT_MIDNIGHT = '0 0 * * 0,6',
    EVERY_WEEKDAY_AT_MIDNIGHT = '0 0 * * 1-5',
    EVERY_WEEKDAY_AT_6AM = '0 6 * * 1-5',
    EVERY_SUNDAY_AT_MIDNIGHT = '0 0 * * 0',
    EVERY_MONDAY_AT_MIDNIGHT = '0 0 * * 1',
    EVERY_FIRST_DAY_OF_MONTH_AT_MIDNIGHT = '0 0 1 * *',
    EVERY_YEAR_AT_MIDNIGHT = '0 0 1 1 *',
}
